version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/learning-experimentation/robofriends-ci-master
    steps:
      - checkout:
          path: ~/learning-experimentation
      - run: echo "npm installing..."
      - run: npm install
      - run: echo "CI=true..."
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout:
          path: ~/learning-experimentation
      - run: echo "start of test..."
      - run: npm install
      - run: npm test
  test_require:
    docker: 
      - image: circleci/node:latest
    - checkout
    - run: echo "testing ::test_require to run in parallel with ::test"
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
        require:
          - test_require
