version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/learning-experimentation/robofriends-ci-master
    steps:
      - checkout:
          path: ~/learning-experimentation
      - run: echo "npm installing..."
      - run: echo "end of install... check directory"
      - run: pwd && ls && cat package.json
      - run: npm install
      - run: echo "CI=true..."
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/learning-experimentation/robofriends-ci-master
    steps:
      - checkout:
          path: ~/robofriends-ci-master
      - run: echo "start of test..."
      - run: npm install
      - run: echo "end of install... check directory"
      - run: pwd && ls && cat package.json
      - run: npm test
  testrequire:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "testing ::test_require to run in parallel with ::test"

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - testrequire
      - test:
          requires:
            - testrequire
