version: 2.1
jobs:
  test_1:
    docker:
      - image: circleci/node:latest
    working_directory: ~/learning-experimentation/robofriends-ci-master
    steps:
      - checkout:
          - path: ~/learning-experimentation
      - run: echo "fml"
workflows:
  version: 2.1
  test_run:
    jobs:
      - test_1
  #   - run: CI=true npm run build
#   test:
#     docker:
#       - image: circleci/node:latest
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run test
#   hithere:
#     docker:
#       - image: circleci/node:latest
#     steps:
#       - checkout
#       - run: echo "Hellloooo!"
# workflows:
#   version: 2
#   build-test-and-lint:
#     jobs:
#       - build
#       - hithere
#       - test:
#           requires:
#             - hithere
